### ISSUE TITLE
[Feature request] Make library entries case-insensitive

### ISSUE THREAD

**Issue by peczony** [tgrbin/Martin#10]
I was trying to figure out why some of my queries are unsuccessful when finally I understood that search is case-sensitive. I think case-insensitive search makes more sense.

**Comment by tgrbin** [comment]
Search is intended to be case-insensitive.
Are you using cyrillic alphabet?
It's likely I'm not lower casing correctly for all the locales, I'll investigate.

**Comment by peczony** [comment]
Yes, I am using cyrillic alphabet.

**Comment by tgrbin** [comment]
This should work now.
