### ISSUE TITLE
Turning Off Notifications

### ISSUE THREAD

**Issue by the-bobo** [tgrbin/Martin#5]
I love this audio player. Lightweight, does what it needs to, open source MIT license, it's great. I wanted to know - is there a way to toggle the notifications it sends to OS X when a song changes? Thank you so much for your work.

**Comment by tgrbin** [comment]
I'm glad you like the player, thanks!

You should be able to disable the notifications through System Preferences -> Notifications.

**Comment by the-bobo** [comment]
Thank you!
