### ISSUE TITLE
Capture keyboard shortcuts only when in focus?

### ISSUE THREAD

**Issue by the-bobo** [tgrbin/Martin#7]
Is there a way to toggle Martin to only capture keyboard shortcuts when the application is selected? I like the way the shortcuts are laid out but some of them interfere with other apps' shortcuts.

**Comment by tgrbin** [comment]
You can disable the global shortcuts through Martin's preferences.
While the app is in focus, you can use the shortcuts from the Control menu.

**Comment by the-bobo** [comment]
Thanks - this would then leave the Control menu shortcuts non-editable by the user, but does provide a way to avoid globally sensitive shortcuts. I ended up changing the global shortcuts instead, thank you!
