### ISSUE TITLE
Non-english input sources are disabled in the search input field

### ISSUE THREAD

**Issue by peczony** [tgrbin/Martin#8]
As said in the title, I can’t enter Russian band/song names via search field because Russian input sources are disabled — greyed out like in password input fields, except unlike passwords where it makes sense, here it just prevents me from searching unicode strings. The search itself works fine: when I copy-paste Russian text into the input field, the correct artists and songs are filtered.

**Comment by tgrbin** [comment]
That sounds really annoying, I'm sorry.
I'll look into it next week.
