### ISSUE TITLE
Crashes when playing a certain file

### ISSUE THREAD

**Issue by peczony** [tgrbin/Martin#9]
http://pastebin.com/GEWheEYy

**Comment by tgrbin** [comment]
Thanks for reporting it!
Would you mind sending the offending file to my email?

**Comment by peczony** [comment]
I’ve just sent it from peczony@gmail.com

**Comment by tgrbin** [comment]
Thank you very much for sending the file.

Seems like disabling last.fm scrobbling prevents the crash.
I'm trying to fix it.

**Comment by tgrbin** [comment]
This should be fixed now.
